Skylar-mobile-check
Watts-Lab/deliberation-empirica pull request #129
Opened 2022-06-21 18:36 UTC by sky1113

checks if user is on mobile and throws an error

2022-06-24 01:26 UTC, JamesPHoughton commented
I believe I'm waiting on a cypress test of this before we merge? Does it seem like a straightforward thing to do, or will it be a lot of work?

2022-06-27 21:06 UTC, sky1113 commented
The test has been added and updated to pass!

2022-06-27 23:05 UTC, JamesPHoughton requested changes
Code looks nice, but the `Normal Paths` and `Batch_Canceled from intro steps` should be working. Did we change something?

2022-06-27 23:05 UTC, JamesPHoughton commented on cypress/e2e/Mobile_Check.js
> +describe("normal_paths", () => {
the name of the test set wants to be changed from "normal_paths" to "mobile_check"

2022-06-27 23:05 UTC, JamesPHoughton commented on cypress/e2e/Mobile_Check.js
> +    cy.wrap(playerKeys, { log: false }).each((playerKey) => {
we only have 1 player in this test, so you can remove line 27 `cy.wrap(playerKeys, { log: false }).each((playerKey) => {` and it's trailing brace, and just have the inside code.

2022-06-28 15:54 UTC, sky1113 commented
Ok, I think this should be good to go, let me know if you find anything else!

2022-06-30 00:01 UTC, JamesPHoughton approved these changes
Thanks @sky1113 - this looks great. =)

2022-06-30 22:59 UTC, merged